// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/games": {
    params: {};
  };
  "/games/:slug": {
    params: {
      "slug": string;
    };
  };
  "/blog": {
    params: {};
  };
  "/blog/:id": {
    params: {
      "id": string;
    };
  };
  "/contact": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/games" | "/games/:slug" | "/blog" | "/blog/:id" | "/contact" | "/*";
  };
  "../src/pages/Home.tsx": {
    id: "../src/pages/Home";
    page: "/";
  };
  "../src/pages/About.tsx": {
    id: "../src/pages/About";
    page: "/about";
  };
  "../src/pages/Games.tsx": {
    id: "../src/pages/Games";
    page: "/games";
  };
  "../src/pages/GameDetail.tsx": {
    id: "../src/pages/GameDetail";
    page: "/games/:slug";
  };
  "../src/pages/Blog.tsx": {
    id: "../src/pages/Blog";
    page: "/blog";
  };
  "../src/pages/BlogPost.tsx": {
    id: "../src/pages/BlogPost";
    page: "/blog/:id";
  };
  "../src/pages/Contact.tsx": {
    id: "../src/pages/Contact";
    page: "/contact";
  };
  "../src/pages/NotFound.tsx": {
    id: "../src/pages/NotFound";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "../src/pages/Home": unknown;
  "../src/pages/About": unknown;
  "../src/pages/Games": unknown;
  "../src/pages/GameDetail": unknown;
  "../src/pages/Blog": unknown;
  "../src/pages/BlogPost": unknown;
  "../src/pages/Contact": unknown;
  "../src/pages/NotFound": unknown;
};